### ISSUE TITLE
JSON not found automatically

### ISSUE THREAD

**Issue by HagarViking** [adsbxchange/adsbexchange-stats#17]
I reinstalled stats today and for some reason it couldn't find JSON by itself (I'm using dump1090-mutability). 

Edited /usr/local/share/adsbexchange-stats/json-status and set the dir. Now it's working.

It seems to only look for /run/adsbexchange-feed:
Status says "No valid data source directory Found.  Tried each of: [/run/adsbexchange-feed]"

**Comment by wiedehopf** [comment]
Reinstall the feed scripts please.
