### ISSUE TITLE
Dnsutils not in repository 

### ISSUE THREAD

**Issue by k8tek** [adsbxchange/adsbexchange-stats#19]
Package dnsutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dnsutils' has no installation candidate

Is there a repository I need to add? This is a plain Rasbian Buster Lite install

**Comment by wiedehopf** [comment]
sudo apt update
then try again?

Should really be available.

**Comment by k8tek** [comment]
I’ve done apt update every day this week and still not in the repo.

**Comment by wiedehopf** [comment]
You can remove the requirement from the install script i suppose and see if it works without it.

Otherwise .... no clue what is going on and i don't have the time to find out what's wrong with your system.

**Comment by adsbxchange** [comment]
Well that's incorrect.  package is in the repo

pi@raspberrypi:~ $ sudo apt install dnsutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libirs161
Suggested packages:
  rblcheck
The following NEW packages will be installed:
  dnsutils libirs161
0 upgraded, 2 newly installed, 0 to remove and 29 not upgraded.
Need to get 596 kB of archives.
After this operation, 952 kB of additional disk space will be used.
Do you want to continue? [Y/n]
