### ISSUE TITLE
jq fails with error: error: syntax error, unexpected IDENT, expecting $end

### ISSUE THREAD

**Issue by mdebusschere** [adsbxchange/adsbexchange-stats#22]
The following are errors are seen repeating in the log
Jan 29 15:33:35 raspberrypi adsbexchange-stats[16533]: error: syntax error, unexpected IDENT, expecting $end
Jan 29 15:33:35 raspberrypi adsbexchange-stats[16533]: try ([.aircraft[].rssi] | select(. >=0) | add / length | floor) catch 0                                                                1 compile error
Jan 29 15:33:35 raspberrypi adsbexchange-stats[16533]: error: syntax error, unexpected IDENT, expecting $end
Jan 29 15:33:35 raspberrypi adsbexchange-stats[16533]: try ([.aircraft[].rssi] | select(. >=0) | min | floor) catch 0                                                       1 compile error
Jan 29 15:33:35 raspberrypi adsbexchange-stats[16533]: error: syntax error, unexpected IDENT, expecting $end
Jan 29 15:33:35 raspberrypi adsbexchange-stats[16533]: try ([.aircraft[].rssi] | select(. >=0) | max | floor) catch 0

It appears jq doesn't like try-catch syntax.    I tried multiple tests on the cli and could not get it to accept it.
Might be a compatibility issue.
I removed the try-catch and it appears to work.

jq --version
jq-1.4-1-e73951f

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

**Comment by adsbxchange** [comment]
Outdated version of jq.

Jessie is not supported.  Suggest stretch or buster.

**Comment by wiedehopf** [comment]
try catch replaced by an if condition, stats package should work on jessie once again.

**Comment by mdebusschere** [comment]
Decided to stick with try / catch vs if condition, hence updated repos to pull latest jq, then updated jq.  
Appears to be working fine on Jessie + piaware  so far..
I will save the full system upgrade for a later date.  
Thanks !
